# vi: ft=yaml.ansible.jinja2
---
fail_fast: true
minimum_pre_commit_version: 3.7.1
exclude: "docs/_build/"
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
  skip:
    # https://github.com/pre-commit-ci/issues/issues/55
    - pip-compile
    - schemas
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-ast
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=123"]
        exclude: >
          (?x)^(
            .pnp.cjs|
            package-lock.json|
            npm-shrinkwrap.json|
            poetry.lock|
            Pipfile.lock|
            yarn.lock|
            sbom.json|
          )$
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
        exclude: >
          (?x)^(
              env/home/log4j.xml
              clean.bat|
              build.bat|
              mvnw.cmd|
              .mvn/|
              .venv|
              .direnv|
              env/winnt|
          )$
      - id: check-shebang-scripts-are-executable
      - id: check-json
        exclude: >
          (?x)^(
            .vscode/|
          )$
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
        exclude: files/startpage.xml/
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: >
          (?x)^(
            .gitlab-ci.yml|
            packs/.*|
            k8s/.*|
          )$
      - id: check-symlinks
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^.cache/
      - id: detect-private-key
        exclude: >
          (?x)^(
              README.md|
              .ssh/id_rsa|
          )$
      # Disable as incompatible with black formatting
      # - id: double-quote-string-fixer
      #   exclude: >
      #     (?x)^(
      #         tests/.*|
      #     )$
      - id: name-tests-test
        exclude: >
          (?x)^(
              molecule/default/tests/test_default.py|
              tests/.*|
          )$
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: file-contents-sorter
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/pre-commit/pre-commit.git
    rev: v4.3.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v25.9.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: >
          (?x)^(
            .travis.yml|
            docker/|
            requirements.yml|
            playbooks/group_vars/all/vault.yml|
            .gitlab-ci.yml|
          )$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1 # or higher tag
    hooks:
     - id: yamllint
       args: [--format, parsable, --strict]
  - repo: https://github.com/doublify/pre-commit-hindent.git
    rev: b3680b6ebf9f7cf29b19307f246adef66756feef
    hooks:
      - id: hindent
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      # Choose one of:
      # - id: shfmt         # native (requires Go to build)
      - id: shfmt-docker  # Docker image (requires Docker to run)
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        args: [-x]
        exclude: >
          (?x)^(
              mvnw|
              hooks|
            tests/.*|
            docs/Makefile|
            .envrc|
              env/linux/.*|
              env/home/dev.env.sh|
              env/home/dotfiles/.*|
              .git-prompt.sh|
          )$
  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v1.0.1
    hooks:
      - id: encryption-check
        exclude: >
          (?x)^(
              .github/workflows/vault.yml|
              infra/terraform/nomad/jobs/vault-backup.nomad|
              infra/terraform/vault/.*|
          )$
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmlhint
        args: [--config, .htmlhintrc]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
#      - id: gitleaks
#        args: [--config, gitleaks.toml]
      - id: gitleaks-docker
        entry: zricethezav/gitleaks protect --verbose --redact --staged
        #entry: zricethezav/gitleaks detect --verbose
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-github-workflows
      - id: check-gitlab-ci
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.43.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
        # args: ['secret', 'scan', 'pre-commit']
  - repo: https://github.com/oxsecurity/megalinter
    rev: v9.0.1
    hooks:
      - id: megalinter-incremental  # Faster, less thorough
        stages:
          - pre-commit
        args:
          - mega-linter-runner
          - --containername
          - "megalinter-incremental"
          - --remove-container
          # - --fix
          # - --env
          # - "'APPLY_FIXES=all'"
          - --env
          - "'CLEAR_REPORT_FOLDER=true'"
          - --env
          - "'LOG_LEVEL=warning'"
          - --filesonly
          - --flavor
          - "python"
