---
language: python
python: "2.7"
env:
  #- ANSIBLE_VERSION=1.4
  #- ANSIBLE_VERSION=1.5
  #- ANSIBLE_VERSION=1.6
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION
script:
  - ansible --version
  - export ANSIBLE_ROLES_PATH="../"
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check conky.yml
  - ansible-playbook -i inventory --connection=local --sudo -vvvv conky.yml
