---

#language: python
#python: "2.7"

cache: bundler
#sudo: false
sudo: required
dist: trusty

env:
  - ANSIBLE_VERSION=2.3.1.0
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - sudo pip install ansible==$ANSIBLE_VERSION
script:
  - sudo ansible --version
  - export ANSIBLE_ROLES_PATH="../"
  - echo localhost > inventory
  - sudo ansible-playbook -i inventory --syntax-check conky.yml
  - sudo ansible-playbook -i inventory --connection=local --sudo -vvvv conky.yml
