---
- hosts: localhost
  gather_facts: yes
  
  tasks:
    - name: run_command
      action: run_cmd cmd=date
      register: user

    - debug: msg="{{ user.msg }}"

  tasks:
    - debug: msg="Hostname is {{ ansible_hostname }}"

- hosts: localhost
  become: true
  gather_facts: true
  
  roles:
    - ./

#  vars:
#       user: root
#       home: "/root"
